<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>law-page</RootNamespace>
    <AssemblyName>$(AssemblyName.Replace(' ', '_'))</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.5.1" />
    <PackageReference Include="Duende.IdentityModel.OidcClient" Version="7.1.0" />
    <PackageReference Include="MudBlazor" Version="9.6.0" />
    <PackageReference Include="QuestPDF" Version="2026.7.0" />
    <PackageReference Include="Radzen.Blazor" Version="11.1.2" />
  </ItemGroup>

</Project>
